[build]
  command = "CI=false npm run build"
  publish="build"
  
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/projects"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/project/*"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/auth/*"
  to ="https://projecttrackcc.herokuapp.com"
  status =200
