[build]
  command = "CI=false npm run build"
  publish="build"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
  from = "/auth"
  to ="https://projecttrackcc.herokuapp.com"
  status =200
